config/routes.rb
Rails.application.routes.draw do
  resources :check_points
  get 'main/index'

  resources :parks

  root "main#index"

end

app/models/check_point.rb
class CheckPoint < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/models/park.rb
# == Schema Information
#
# Table name: parks
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  latitude   :float
#  longitude  :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Park < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_points_controller.rb
class CheckPointsController < ApplicationController
  before_action :set_check_point, only: [:show, :edit, :update, :destroy]

  # GET /check_points
  # GET /check_points.json
  def index
    @check_points = CheckPoint.all

    @polylines = []
    @check_points.each_with_index do |row, i|
      next_row = @check_points[i + 1]
      if next_row.nil?
        next_row = @check_points.first
      end

      hash = [
        {lat: row.latitude, lng: row.longitude},
        {lat: next_row.latitude, lng: next_row.longitude}
      ]
      @polylines << hash
    end
  end

  # GET /check_points/1
  # GET /check_points/1.json
  def show
    @hash = Gmaps4rails.build_markers(@check_point) do |check_point, marker|
      marker.lat check_point.latitude
      marker.lng check_point.longitude
      marker.infowindow check_point.address
      marker.json({title: check_point.address})
    end
  end

  # GET /check_points/new
  def new
    @check_point = CheckPoint.new
  end

  # GET /check_points/1/edit
  def edit
  end

  # POST /check_points
  # POST /check_points.json
  def create
    @check_point = CheckPoint.new(check_point_params)
    @check_point.latitude = check_point_params[:latitude].to_f
    @check_point.longitude = check_point_params[:longitude].to_f

# binding.pry
p @check_point
    respond_to do |format|
      if @check_point.save
        format.html { redirect_to @check_point, notice: 'Check point was successfully created.' }
        format.json { render :show, status: :created, location: @check_point }
      else
        format.html { render :new }
        format.json { render json: @check_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_points/1
  # PATCH/PUT /check_points/1.json
  def update
    respond_to do |format|
      if @check_point.update(check_point_params)
        format.html { redirect_to @check_point, notice: 'Check point was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_point }
      else
        format.html { render :edit }
        format.json { render json: @check_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_points/1
  # DELETE /check_points/1.json
  def destroy
    @check_point.destroy
    respond_to do |format|
      format.html { redirect_to check_points_url, notice: 'Check point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_point
      @check_point = CheckPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_point_params
      params.require(:check_point).permit(:address, :latitude, :longitude)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @parks = Park.all
    @hash = Gmaps4rails.build_markers(@parks) do |park, marker|
      marker.lat park.latitude
      marker.lng park.longitude
      marker.infowindow park.address
      marker.json({title: park.name})
    end

    @polylines = []
    @parks.each_with_index do |row, i|
      next_row = @parks[i + 1]
      if next_row.nil?
        next_row = @parks.first
      end


      hash = [
        {lat: row.latitude, lng: row.longitude},
        {lat: next_row.latitude, lng: next_row.longitude}
      ]
      @polylines << hash
    end
  end
end

app/controllers/parks_controller.rb
# == Schema Information
#
# Table name: parks
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  latitude   :float
#  longitude  :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ParksController < ApplicationController
  before_action :set_park, only: [:show, :edit, :update, :destroy]

  # GET /parks
  # GET /parks.json
  def index
    @parks = Park.all
  end

  # GET /parks/1
  # GET /parks/1.json
  def show
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
  end

  # POST /parks
  # POST /parks.json
  def create
    @park = Park.new(park_params)

    respond_to do |format|
      if @park.save
        format.html { redirect_to @park, notice: 'Park was successfully created.' }
        format.json { render :show, status: :created, location: @park }
      else
        format.html { render :new }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parks/1
  # PATCH/PUT /parks/1.json
  def update
    respond_to do |format|
      if @park.update(park_params)
        format.html { redirect_to @park, notice: 'Park was successfully updated.' }
        format.json { render :show, status: :ok, location: @park }
      else
        format.html { render :edit }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.json
  def destroy
    @park.destroy
    respond_to do |format|
      format.html { redirect_to parks_url, notice: 'Park was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
      params.require(:park).permit(:name, :address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_points_helper.rb
module CheckPointsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/parks_helper.rb
# == Schema Information
#
# Table name: parks
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  latitude   :float
#  longitude  :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module ParksHelper
end

app/views/check_points/_form.html.erb
<%= form_for(@check_point) do |f| %>
  <% if @check_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_point.errors.count, "error") %> prohibited this check_point from being saved:</h2>

      <ul>
      <% @check_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_points/edit.html.erb
<h1>Editing Check Point</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_point %> |
<%= link_to 'Back', check_points_path %>

app/views/check_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Check Points</h1>

<div style='width: 100%;'>
  <div id="multi_overlays" style='width: 100%; height: 400px;'></div>
</div>
<script type="text/javascript">
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'multi_overlays'}}, function(){

    var polylines = handler.addPolylines(
      <%=raw @polylines.to_json %>,
      { strokeColor: 'blue'}
    );
    handler.bounds.extendWith(polylines);
    handler.fitMapToBounds();

  });
</script>


<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_points.each do |check_point| %>
      <tr>
        <td><%= check_point.address %></td>
        <td><%= check_point.latitude %></td>
        <td><%= check_point.longitude %></td>
        <td><%= link_to 'Show', check_point %></td>
        <td><%= link_to 'Edit', edit_check_point_path(check_point) %></td>
        <td><%= link_to 'Destroy', check_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check point', new_check_point_path %>

app/views/check_points/new.html.erb
<h1>New Check Point</h1>

<div style='width: 100%;'>
  <div id="geolocation" style='width: 100%; height: 400px;'></div>
</div>
<script type="text/javascript">
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
  });

  function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude
  });
  handler.map.centerOn(marker);

  $("#check_point_latitude").val(marker.serviceObject.position.G);
  $("#check_point_longitude").val(marker.serviceObject.position.K);
  };
</script>


<%= render 'form' %>

<%= link_to 'Back', check_points_path %>

app/views/check_points/show.html.erb
<p id="notice"><%= notice %></p>

<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    styles: [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":"61"},{"lightness":"25"},{"hue":"#ff003c"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#46e9ec"},{"visibility":"on"}]}]
  },
  internal: {id: 'map'}},
  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

  // var handler = Gmaps.build('Google');
  // handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  // if(navigator.geolocation)
  //   navigator.geolocation.getCurrentPosition(displayOnMap);
  // });
  //
  // function displayOnMap(position){
  // var marker = handler.addMarker({
  //   lat: position.coords.latitude,
  //   lng: position.coords.longitude
  // });
  // handler.map.centerOn(marker);
  // };
</script>

<p>
  <strong>Address:</strong>
  <%= @check_point.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @check_point.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @check_point.longitude %>
</p>


<%= link_to 'Edit', edit_check_point_path(@check_point) %> |
<%= link_to 'Back', check_points_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapOneStorkeSketch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<div style='width: 100%'>
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<script type="text/javascript">

    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      styles: [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":"61"},{"lightness":"25"},{"hue":"#ff003c"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#46e9ec"},{"visibility":"on"}]}]
    },
    internal: {id: 'map'}},
    function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });


    // handler.buildMap({ internal: {id: 'map'} }, function(){
    //   if(navigator.geolocation)
    //     navigator.geolocation.getCurrentPosition(displayOnMap);
    // });
    //
    // function displayOnMap(position){
    //   var marker = handler.addMarker({
    //     lat: position.coords.latitude,
    //     lng: position.coords.longitude
    //   });
    //   handler.map.centerOn(marker);
    // };



    var polylines = handler.addPolylines(
      <%=raw @polylines.to_json %>,
      // [
      //   [
      //     {lat: 34.97338450000001, lng: 138.3821125},
      //     {lat: 35.0343254, lng: 138.422258}
      //   ],
      //   [
      //     {lat: 35.0343254, lng: 138.422258},
      //     {lat: 35.0456756, lng: 138.3664488}
      //   ]
      // ],
      { strokeColor: 'blue'}
    );
    handler.bounds.extendWith(polylines);
    handler.fitMapToBounds();

</script>

app/views/parks/_form.html.erb
<%= form_for(@park) do |f| %>
  <% if @park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@park.errors.count, "error") %> prohibited this park from being saved:</h2>

      <ul>
      <% @park.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parks/edit.html.erb
<h1>Editing Park</h1>

<%= render 'form' %>

<%= link_to 'Show', @park %> |
<%= link_to 'Back', parks_path %>

app/views/parks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parks.each do |park| %>
      <tr>
        <td><%= park.name %></td>
        <td><%= park.address %></td>
        <td><%= park.latitude %></td>
        <td><%= park.longitude %></td>
        <td><%= link_to 'Show', park %></td>
        <td><%= link_to 'Edit', edit_park_path(park) %></td>
        <td><%= link_to 'Destroy', park, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Park', new_park_path %>

app/views/parks/new.html.erb
<h1>New Park</h1>

<%= render 'form' %>

<%= link_to 'Back', parks_path %>

app/views/parks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @park.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @park.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @park.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @park.longitude %>
</p>

<%= link_to 'Edit', edit_park_path(@park) %> |
<%= link_to 'Back', parks_path %>